accounts/urls.py
from django.urls import path
from . import views

# Define the app namespace
app_name = "accounts"


urlpatterns = [
    # path("login_register/", views.user_login_register, name="login_register"),
    path("login/", views.user_login, name="login"),
    path("register/", views.user_register, name="register"),
    path("logout/", views.user_logout, name="logout"),
    path("dashboard/", views.user_dashboard, name="dashboard"),
    path("enroll_the_course/", views.enroll_the_course, name="enroll_the_course"),
    path("release_the_course/", views.release_the_course, name="release_the_course"),
]

core/urls.py
# MEDIA FILES CONFIG
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("pages.urls")),  # http://127.0.0.1:8000/...
    path("admin/", admin.site.urls),  # http://127.0.0.1:8000/admin/
    path("courses/", include("courses.urls")),  # http://127.0.0.1:8000/courses/...
    path("trainers/", include("trainers.urls")),  # http://127.0.0.1:8000/trainers/...
    path("accounts/", include("accounts.urls")),  # http://127.0.0.1:8000/accounts/...
]
# handler404 = "pages.views.custom_404"
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Serve static and media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from courses import views

# Define the app namespace
app_name = 'courses'  


urlpatterns = [
    # path('',views.course_list,name="courses"),  
    # path("<slug:category_slug>/<int:course_id>/",views.course_detail,name="course_detail"),
    path("categories/<slug:category_slug>/",views.categories_detail,name="courses_by_category"),
    path("tags/<slug:tag_slug>/",views.tags_detail,name="courses_by_tag"),
    path("programs/list/",views.show_by_array,name="show_by_array"),
    path("programs/<str:text>/",views.show_by_text,name="show_by_text"),
    path("programs/unenrolled/",views.user_unenrolled_course,name="User_unenrolled_courses"),
    #! enroll and release course
    path("enroll/<int:course_id>/",views.enroll_course,name="enroll_course"),
    path("release/<int:course_id>/",views.release_course,name="release_course"),
    path("dashboard/",views.dashboard__page,name="dashboard"),
] 

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm as AuthForm

from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class RegisterForm(UserCreationForm):
    # Customizing the username field
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",  # Adding a custom CSS class
                "placeholder": "Username",
                "autocomplete": "username",
            }
        )
    )

    # Customizing the email field
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",  # Adding a custom CSS class
                "placeholder": "Email",  # Placeholder text
                "autocomplete": "email",  # HTML5 autocomplete attribute
            }
        )
    )
    # Customizing the firstname field
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",  # Adding a custom CSS class
                "placeholder": "Firstname",  # Placeholder text
                "autocomplete": "firstname",  # HTML5 autocomplete attribute
                "id": "id_register_firstname",
            }
        )
    )
    # Customizing the lastname field
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",  # Adding a custom CSS class
                "placeholder": "Lastname",  # Placeholder text
                "autocomplete": "lastname",  # HTML5 autocomplete attribute
                "id": "id_register_lastname",
            }
        )
    )

    # Customizing the password1 field
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",  # Adding a custom CSS class
                "placeholder": "Password",
                "autocomplete": "new-password",
            }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",  # Adding a custom CSS class
                "placeholder": "Confirm Password",
                "autocomplete": "new-password",
            }
        )
    )

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]


class LoginForm(AuthForm):
    # !No widget
    # username = forms.CharField(max_length=254)
    # password = forms.CharField(widget=forms.PasswordInput)
    # ? use widget
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "name": "username",
                "type": "text",
                "class": "form-control",
                "placeholder": "Username",
                "id": "id_login_username",
                "autocomplete": "username",  # Autocomplete attribute for better UX
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "name": "password",
                "type": "password",
                "class": "form-control",
                "placeholder": "Password",
                "id": "id_login_password",
                "autocomplete": "current-password",
            }
        )
    )


# class LoginForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput)

#     class Meta:
#         model = User
#         fields = ["username", "password"]

#     def clean(self):
#         username = self.cleaned_data.get("username")
#         password = self.cleaned_data.get("password")
#         user = authenticate(username=username, password=password)

#         if not user:
#             raise forms.ValidationError("Invalid username or password !")

#         return self.cleaned_data

accounts/views.py
from django.shortcuts import render, redirect
from django.urls.base import reverse
from .forms import LoginForm, RegisterForm
from django.contrib.auth import login, logout, authenticate

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from courses.models import Course
from django.contrib.auth.models import User


# def user_login_register(request):
#     if request.method == "POST":
#         if "register" in request.POST:
#             register_form = RegisterForm(request.POST)
#             login_form = LoginForm()
#             if register_form.is_valid():
#                 user = register_form.save()
#                 login(request, user)
#                 messages.success(request, "Register successful!")
#                 return redirect("accounts:login_register")
#             messages.error(request, "Invalid username or password.")

#         elif "login" in request.POST:
#             login_form = LoginForm(request, data=request.POST)
#             register_form = RegisterForm()
#             if login_form.is_valid():
#                 user = login_form.get_user()
#                 login(request, user)
#                 messages.success(request, "Login successful!")
#                 return redirect("home")
#             messages.error(request, "Invalid username or password")

#     else:
#         register_form = RegisterForm()
#         login_form = LoginForm()


#     return render(
#         request,
#         "accounts/login_register.html",
#         {"register_form": register_form, "login_form": login_form},
#     )


def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request, data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            # Set the session variable only if this is the user's first login
            # if "first_login" not in request.session:
            #     request.session["first_login"] = True  # First successful login flag
            request.session["login_success"] = True
            messages.success(request, "Login successful!")
            return redirect("home")
        messages.error(request, "Invalid username or password")
    login_form = LoginForm()
    if request.user.is_authenticated:
        return render(request, "home.html")

    return render(request, "accounts/login.html", {"form": login_form})


def user_register(request):
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user = register_form.save()
            # login(request, user)
            request.session["register_success"] = True
            messages.info(request, "Register successful!")
            return redirect("accounts:login")
        messages.error(request, "Invalid form Filled.")
    if request.user.is_authenticated:
        return render(request, "home.html")
    register_form = RegisterForm()
    return render(request, "accounts/register.html", {"form": register_form})


def user_logout(request):
    logout(request)
    return redirect("home")


@login_required(login_url="login")
def user_dashboard(request):
    current_user = request.user
    courses = current_user.courses_joined.all()
    context = {
        "courses": courses,
    }
    return render(request, "accounts/dashboard.html", context)
    pass


def enroll_the_course(request):
    user_id = request.POST["user_id"]
    course_id = request.POST["course_id"]
    course = Course.objects.get(id=course_id)
    user = User.objects.get(id=user_id)

    course.students.add(user)
    return redirect("dashboard")



def release_the_course(request):
    user_id = request.POST["user_id"]
    course_id = request.POST["course_id"]
    course = Course.objects.get(id=course_id)
    user = User.objects.get(id=user_id)

    course.students.remove(user)
    return redirect("dashboard")

templates/accounts/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block title %} Dashboard {% endblock title %}


{% block custom_css %} 
<link rel="stylesheet" href="{% static 'css/accounts/dashboard/style.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/dashboard/responsive.css' %}">
{% endblock custom_css %}


{% comment %} ?--- Content ---* {% endcomment %}
{% block content %}

<section class="dashboard  softlightmode">
   

    <div class="container ">
     
      <div class="head_caption">
        <div class="head_title">My Enrolled Courses</div>
      </div>

      {% if courses %}
      <div class="catalogList">
          {% for course in courses %}

          <div class="card" >
                <div class="card_content" >
                {% comment %} < class="card" href="{% url 'programs_detail' course.id %}"> {% endcomment %}
                  <div class="cardPreview">
                      <img class="backPreview" src="{{course.image.url}}" alt="">
                      <div class="cardStatus {{ course.category.slug }}">{{ course.category.name }}</div>
                  </div>
            
                  <div class="cardHead">
                      <div class="cardUser">
                          <div class="cardAvatar">
                              <img src="{{ course.trainer.image.url}}" alt="">
                          </div>
                          <div class="cardDetails">
                              <div class="cardTitle">{{ course.description|truncatechars:16}}</div>
                              <div class="cardTrainer">
                                  <span class="fullname">{{course.trainer.fullname}}</span>
                              </div>
                          </div>
                      </div>
                      <div class="cardLevel {{course.level.name}}">{{course.level.name}}</div>
                  </div>
            
                  <div class="cardParameters">
                      <div class="cardParameter">
                          <i class="fa-brands fa-youtube"></i>
                          <span>7</span> 
                      </div>
                      <div class="cardParameter">
                          <i class="fa-regular fa-user"></i>
                        <span>160</span>
                      </div>
                  </div>
              </div>
              {% if user.is_authenticated %}
              {% if course in user.courses_joined.all %}
                <form class="release_form" action="{% url 'courses:release_course' course.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="release release_btn">Release</button>
                </form>                       
              {% endif %}
              {% endif %}
            </div>
          {% endfor %}
        </div>

      {% else %}
        <div class="not_enrolled_courses">You are not enrolled in any courses yet.</div>
      {% endif %} 

    </div>


  </div>
</div>
 
    

</div>
</section>

{% endblock content %}
{% comment %} ?--- Content ---* {% endcomment %}

{% block custom_js %}
    <script src="{% static '/js/dashboard/dashboard.js' %}"></script>
    {% comment %} <script src="{% static '/js/dashboard/anime.js' %}"></script> {% endcomment %}
{% endblock custom_js  %}

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block title %} Login {% endblock title %}


{% block custom_css %} 
<link rel="stylesheet" href="{% static 'css/accounts/login/style.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/login/responsive.css' %}">
{% endblock custom_css %}


{% comment %} ?--- Content ---* {% endcomment %}
{% block content %}


{% comment %}  {% endcomment %}
<section class="login_page lightmode">
    

    <div class="container">
        <div class="login-wrapper ">

            <div class=" box-image box-col">
            <img class="some-icon-light" src="{% static "assets/images/accounts/login/sideimage_light.png" %}" alt="sideimage"> 
            <img class="some-icon-dark" src="{% static "assets/images/accounts/login/sideimage_dark.png" %}" alt="sideimage"> 
            </div>
            <div class="box-col">
               <div class="box-form">
                   <div class="inner">
                       <form class="form-head" method="POST">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                           <div class="title">
                               Login Page
                           </div>
                           <div class="form-group">
                               <label class="label-text" for="id_login_username">Username</label>
                               {{form.username}}
                               {% if form.username.errors %}
                                    <div class="error">{{ form.username.errors }}</div>
                                {% endif %}
                               {% comment %} <input type="text" placeholder="Username" name="username" id="id_login_username" value=""> {% endcomment %}
                           </div>
                           <div class="form-group">
                               <label class="label-text" for="id_login_password">Password</label>
                               {% comment %} <input type="password" placeholder="Password" name="password" id="id_login_password" > {% endcomment %}
                               {{form.password}}
                               {{form.password.errors}}
                           </div>
                           {% comment %} 
                                <div class="form-button">
                                    <div class="check-action">
                                        <input type="checkbox" class="check">
                                        <span class="name">Remember Me</span>
                                    </div>
                                    <a href="#" class="link">Forgot Password?</a>
                                </div> 
                           {% endcomment %}
        
                           <div class="actions">
                               <button type="submit" class="btn btn-submit">Login Now</button>
                               {% comment %} 
                                    <button class="btn btn-google">
                                        <span class="icon">
                                            <img src="img/google.png" alt="google">
                                            Or Sign-in with Google
                                        </span>
                                    </button> 
                               {% endcomment %}
                           </div>
                       </form>
                       <div class="bottom-register">
                            <span class="remember_text">Don't have an account?</span>
                            <a href="{% url "accounts:register" %}" class="link register_link">Join free Today!</a>
                       </div>
                       <p class="error_text">
                            {% if messages %}
                                {% for message in messages %}
                                    {% if message.tags == 'error' %}
                                        <div class="custom_alert alert-error">
                                        {{ message }}
                                        </div>
                                    {% endif %}
                                    {% if message.tags == 'info' %}
                                        <div class="custom_alert alert-success">
                                        {{ message }}
                                        </div>
                                    {% endif %}  
                                {% endfor %}
                            {% endif %} 
                       </p>
                   </div>
               </div>
        
              
            </div>
        </div>
    </div>
</section>
{% comment %}  {% endcomment %}


{% endblock content %}
{% comment %} ?--- Content ---* {% endcomment %}

{% block custom_js %}
    <script src="{% static '/js/accounts/login.js' %}"></script>
{% endblock custom_js  %}

templates/accounts/login_register.html
{% extends "base.html" %}
{% load static %}
{% block title %} Login {% endblock title %}


{% block custom_css %} 
<link rel="stylesheet" href="{% static 'css/accounts/login_register/style.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/login_register/responsive.css' %}">
{% endblock custom_css %}


{% comment %} ?--- Content ---* {% endcomment %}
{% block content %}


{% comment %}  {% endcomment %}
<section class="loginPage lightmode">

{% comment %}  {% endcomment %}


<div class="container">
    <div class="context_warpper">
        <div class="context">
            <div class="signin-signup">
                <form  class="sign-in-form form_tag" method="POST">
                    {% csrf_token %}
                    <h2 class="title">Sign in</h2>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        {% comment %} <input type="text" placeholder="Username" name="username" id="id_login_username" value=""> {% endcomment %}
                        {{login_form.username}}
                    </div>

                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        {% comment %} <input type="password" placeholder="Password" name="password" id="id_login_password" > {% endcomment %}
                        {{login_form.password}}
                    </div>
                   
                    <button type="submit"  name="login"  class="btn_submit" id="login_button" >Login</button>
                    <p class="account-text-login">
                        {% comment %} {% if login_form.non_field_errors %}
                            <div class="error">
                                {% for error in login_form.non_field_errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %} {% endcomment %}
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                                    <div class="alert alert-error">
                                    {{ message }}
                                    </div>
                                {% endif %} 
                            {% endfor %}
                        {% endif %} 
                    </p>
                </form>
                <form  class="sign-up-form form_tag" method="POST">
                    {% csrf_token %}
                    <h2 class="title">Sign up</h2>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        <input required type="text" placeholder="Username" name="username" id="id_register_username" value="">
                    </div>
                    <div class="input-field">
                        <i class="fas fa-envelope"></i>
                        <input required type="email" placeholder="Email" name="email" id="id_register_email" value="">
                    </div>
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        <input required type="password" placeholder="Password"  name="password1" id="id_register_password1">
                        {% comment %} {% if register_form.password1.errors %}
                            <div>{{ register_form.password1.errors }}</div>
                        {% endif %} {% endcomment %}
                    </div>
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        <input required type="password" placeholder="Confirm Password" name="password2" id="id_password2">
                    </div>
                    <button type="submit" name="register"  class="btn_submit">Sign up</button>
                    {% comment %} <p class="account-text">Already have an account? <a href="#" id="sign-in-btn2">Sign in</a></p> {% endcomment %}
                </form>
            </div>
            <div class="panels-container">
                <div class="panel left-panel">
                    <div class="content">
                        <h3>Member of Brand?</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque accusantium dolor, eos incidunt minima iure?</p>
                        <button class="btn_submit" id="sign-in-btn">Sign in</button>
                    </div>
                </div>
                <div class="panel right-panel">
                    <div class="content">
                        <h3>New to Brand?</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque accusantium dolor, eos incidunt minima iure?</p>
                        <button class="btn_submit" id="sign-up-btn">Sign up</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


{% comment %}  {% endcomment %}

</section>

{% comment %}  {% endcomment %}

{% endblock content %}
{% comment %} ?--- Content ---* {% endcomment %}

{% block custom_js %}
    {% comment %} <script src="{% static '/js/login/login.js' %}"></script> {% endcomment %}
    <script src="{% static '/js/accounts/login_register.js' %}"></script>
{% endblock custom_js  %}

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block title %} Register {% endblock title %}


{% block custom_css %} 
<link rel="stylesheet" href="{% static 'css/accounts/register/style.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/register/responsive.css' %}">
{% endblock custom_css %}


{% comment %} ?--- Content ---* {% endcomment %}
{% block content %}

<section class="login_page lightmode">
    <div class="container">
        <div class="login-wrapper ">
            <div class="box-image box-col box-col-left">
                <img class="some-icon-light" src="{% static "assets/images/accounts/login/sideimage_light.png" %}" alt="sideimage"> 
                <img class="some-icon-dark" src="{% static "assets/images/accounts/login/sideimage_dark.png" %}" alt="sideimage"> 
            </div>

            <div class="box-form box-col box-col-right">
                <div class="inner">
                    <form class="form-head" method="POST">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% comment %} <div class="title">Register Page</div> {% endcomment %}
                        
                        <div class="form-group">
                            {% comment %} <div class="label-text">Username</div> {% endcomment %}
                            {% comment %} <input class="form-control" required type="text" placeholder="Username" name="username" id="id_register_username" value=""> {% endcomment %}
                            {{ form.username }}
                            {{ form.username.errors }}
                        </div>

                        <div class="form-group">
                            {% comment %} <label class="label-text" for="id_register_email">Email</label> {% endcomment %}
                            {% comment %} <input class="form-control" required type="email" placeholder="Email" name="email" id="id_register_email" value=""> {% endcomment %}
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>

                        <div class="form-group-custom">
                            <div class="form_user form_group_left">
                                {% comment %} <label class="label-text" for="id_register_email">Firstname</label> {% endcomment %}
                                {% comment %} <input class="form-control" required type="email" placeholder="Firstname" name="firstname" id="id_register_firstname" value=""> {% endcomment %}
                                {{form.first_name}}
                            </div>
                            <div class="form_user form_group_left">
                                {% comment %} <label class="label-text" for="id_register_email">Lastname</label> {% endcomment %}
                                {% comment %} <input class="form-control" required type="email" placeholder="Lastname" name="Lastname" id="id_register_lastname" value=""> {% endcomment %}
                                {{form.last_name}}

                            </div>
                        </div>


                        <div class="form-group">
                            {% comment %} <div class="label-text">Password</div> {% endcomment %}
                            {% comment %} <input class="form-control" class="form-control" required type="password" placeholder="Password"  name="password1" id="id_register_password1"> {% endcomment %}
                            {{form.password1}}
                            {{form.password1.errors}}
                        </div>

                        <div class="form-group">
                            {% comment %} <div class="label-text">Confirm Password</div> {% endcomment %}
                            {% comment %} <input class="form-control" required type="password" placeholder="Confirm Password" name="password2" id="id_password2"> {% endcomment %}
                            {{form.password2}}
                            {{form.password2.errors}}

                        </div>
                        <div class="actions">
                            <button type="submit" class="btn btn-submit">Register</button>
                        </div>
                    </form>
                    <div class="bottom-register">
                        <span class="remember_text">You have an account?</span>
                        <a href="{% url "accounts:login" %}" class="link register_link">Log in here</a>
                    </div>
                    <p class="error_text">
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                                    <div class="custom_alert alert-error">
                                    {{ message }}
                                    </div>
                                {% endif %} 
                            {% endfor %}
                        {% endif %} 
                   </p>
                </div>
            </div>
        </div>
        
    </div>
</section>
{% endblock content %}
{% comment %} ?--- Content ---* {% endcomment %}

{% block custom_js %}
    <script src="{% static '/js/accounts/register.js' %}"></script>
{% endblock custom_js  %}