accounts/urls.py
from django.urls import path
from . import views

# Define the app namespace
app_name = "accounts"


urlpatterns = [
    # path("login_register/", views.user_login_register, name="login_register"),
    path("login/", views.user_login, name="login"),
    path("register/", views.user_register, name="register"),
    path("logout/", views.user_logout, name="logout"),
    path("dashboard/", views.user_dashboard, name="dashboard"),
    path("enroll_the_course/", views.enroll_the_course, name="enroll_the_course"),
    path("release_the_course/", views.release_the_course, name="release_the_course"),
]

core/urls.py
# MEDIA FILES CONFIG
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("pages.urls")),  # http://127.0.0.1:8000/...
    path("admin/", admin.site.urls),  # http://127.0.0.1:8000/admin/
    path("courses/", include("courses.urls")),  # http://127.0.0.1:8000/courses/...
    path("trainers/", include("trainers.urls")),  # http://127.0.0.1:8000/trainers/...
    path("accounts/", include("accounts.urls")),  # http://127.0.0.1:8000/accounts/...
]
# handler404 = "pages.views.custom_404"
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Serve static and media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from courses import views

# Define the app namespace
app_name = 'courses'  


urlpatterns = [
    # path('',views.course_list,name="courses"),  
    # path("<slug:category_slug>/<int:course_id>/",views.course_detail,name="course_detail"),
    path("categories/<slug:category_slug>/",views.categories_detail,name="courses_by_category"),
    path("tags/<slug:tag_slug>/",views.tags_detail,name="courses_by_tag"),
    path("programs/list/",views.show_by_array,name="show_by_array"),
    path("programs/<str:text>/",views.show_by_text,name="show_by_text"),
    path("programs/unenrolled/",views.user_unenrolled_course,name="User_unenrolled_courses"),
    #! enroll and release course
    path("enroll/<int:course_id>/",views.enroll_course,name="enroll_course"),
    path("release/<int:course_id>/",views.release_course,name="release_course"),
    path("dashboard/",views.dashboard__page,name="dashboard"),
] 

templates/class_01_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Class 01 detail{% endblock title %}

{% comment %} {% block custom_favicon %}{% endblock custom_favicon %} {% endcomment %}

{% block swiper_css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
{% endblock swiper_css %}

{% block custom_css %} 
<link rel="stylesheet" href="{% static 'css/class_01_detail/style.css' %}">
<link rel="stylesheet" href="{% static 'css/class_01_detail/responsive.css' %}">
{% endblock custom_css %}


{% comment %} *--- Content ---* {% endcomment %}
{% block content %}


 {% comment %}? <!--? description Start --> {% endcomment %}
 <section class="description lightmode">
    <div class="container">

        <div class="descriptionWrapper">
            <div class="descriptionRow">
                <div class="descriptionLeftCol">
                    <div class="descriptionDetails">
                        <span class="category">{{ course.category.name}}</span>
                        <span class="release">new release</span>
                    </div>
                    <h2 class="descroptionTitle">{{course.title}}</h2>
                    <div class="descriptionInfo">
                        {% comment %} A 7-days training program designed to boost your strength &
                        endurance over the course of a week. {% endcomment %}
                        {{course.description}}
                    </div>
                </div>

                <div class="descriptionRightCol">
                    <div class="descriptionGroup">

                        <div class="descriptionItem">
                            <div class="left">
                                <img src="{% static 'assets/images/class_01_detail/description/calendar.svg' %}" alt="">
                                <span>Classes</span>
                            </div>
                            <span class="detailInfo">{{course.classes}}</span>
                        </div>
                        <div class="descriptionItem">
                            <div class="left">
                                <img src="{% static 'assets/images/class_01_detail/description/clock.svg' %}" alt="">
                                <span>Average duration</span>
                            </div>
                            <span class="detailInfo">{{course.duration}} minutes</span>
                        </div>
                        <div class="descriptionItem">
                            <div class="left">
                                <img src="{% static 'assets/images/class_01_detail/description/scoreboard.svg' %}" alt="">
                                <span>Difficulity</span>
                            </div>
                            <span class="detailInfo">{{ course.level.name }}</span>
                        </div>
                        <div class="descriptionItem">
                            <div class="left">
                                <img src="{% static 'assets/images/class_01_detail/description/candlesticks.svg' %}" alt="">
                                <span>Intensity</span>
                            </div>
                            <span class="detailInfo">{{ course.intensity.name}}</span>
                        </div>

                    </div>
                    <div class="divider"></div>
                </div>
            </div>

            <div class="descriptionRow">

                <div class="descriptionLeftCol">
                    <div class="descriptionPreview">
                        {% comment %} <img src="{% static 'assets/images/class_01_detail/description/workout-pic.png' %}" alt=""> {% endcomment %}
                        <img src="{{course.image.url}}" alt="">

                    </div>
                </div>

                <div class="descriptionRightCol">
                    <div class="descriptionText">
                        <p>A seven-day bodyweight training program designed to boost your strength and endurance
                            over
                            the course of a week.
                        </p>
                        <p>In this series, you will:</p>
                    </div>

                    <ul class="descriptionList">
                        <li>
                            <img src=" {% static 'assets/images/class_01_detail/description/check.svg' %}" alt="">
                            <span> Get a full strength and cardio workout — no equipment necessary</span>
                        </li>
                        <li> <img src="{% static 'assets/images/class_01_detail/description/check.svg' %}" alt="">
                            <span> Strengthen and tone your entire body </span>
                        </li>
                        <li>
                            <img src="{% static 'assets/images/class_01_detail/description/check.svg' %}" alt="">
                            <span> Increase your balance, flexibility, and endurance</span>
                        </li>
                    </ul>

                    <div class="desriptionBtns">
                        <button class="btnLock">
                            <img src="{% static 'assets/images/class_01_detail/description/lock.svg' %}" alt="">
                        </button>
                        <button class="btn btn_orange">Start free trial</button>
                    </div>
                </div>

            </div>


        </div>


        <div class="interesting">
            <div class="top">
                <h2 class="interestingTitle">You may interested</h2>
                <div class="direction_btns">
                    <button class="slickPrev direction"><i class="fa-solid fa-left-long"></i></button>
                    <button class="slickNext direction"><i class="fa-solid fa-right-long"></i></button>
                </div>
            </div>

            <div class="content">
                <div class="swiper">
                    <div class="swiper-wrapper">

                        {% for course  in courses %}
                        <a href="{% url 'programs_detail' course.id %}" class="card swiper-slide">
                                <div class="cardPreview">
                                    {% comment %} <img src="{% static 'assets/images/class_01_detail/catalogList/card-pic-1.png' %}" alt=""> {% endcomment %}
                                    <img src="{{course.image.url}}" alt="">
                                    <div class="cardStatus yoga">{{course.category.name}}</div>
                                </div>

                                <div class="cardHead">
                                    <div class="cardUser">
                                        <div class="cardAvatar">
                                            <img src="{{course.trainer.image.url}}" alt="">
                                        </div>
                                        <div class="cardDetails">
                                            <div class="cardTitle">7-days barre body</div>
                                            <div class="cardTrainer">
                                                <span class="fullname">{{course.trainer.fullname}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="cardLevel {{course.level|lower}}">{{course.level}}</div>
                                </div>

                                <div class="cardParameters">
                                    <div class="cardParameter">
                                        <i class="fa-brands fa-youtube"></i>160
                                    </div>
                                    <div class="cardParameter">
                                        <i class="fa-regular fa-user"></i>7
                                    </div>
                                </div>
                        </a>
                        {% endfor %}


                        {% comment %} {% for course  in courses %}
                            <div class="card swiper-slide">
                                <div class="cardPreview">
                                    <img src="{{course.image.url}}" alt="">
                                    <div class="cardStatus yoga">{{course.category.name}}</div>
                                </div>

                                <div class="cardHead">
                                    <div class="cardUser">
                                        <div class="cardAvatar">
                                            <img src="{{course.trainer.image.url}}" alt="">
                                        </div>
                                        <div class="cardDetails">
                                            <div class="cardTitle">7-days barre body</div>
                                            <div class="cardTrainer">
                                                <span class="fullname">{{course.trainer.fullname}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="cardLevel {{course.level|lower}}">{{course.level}}</div>
                                </div>

                                <div class="cardParameters">
                                    <div class="cardParameter">
                                        <i class="fa-brands fa-youtube"></i>160
                                    </div>
                                    <div class="cardParameter">
                                        <i class="fa-regular fa-user"></i>7
                                    </div>
                                </div>
                            </div>
                        {% endfor %} {% endcomment %}


                            
                            

                    </div>  
                    
                    {% comment %}? include card html {% endcomment %}
                        {% comment %} {% include "includes_partials/catalog_cards.html" %} {% endcomment %}
                    {% comment %}! include card html {% endcomment %}

                   
                </div>
            </div>

            {% comment %} <div class="interestingBtn">
                <button class="discoverMore">Browser more</button>
                <button class="tDiscoverMore">
                    <span>Discover more </span>
                    <i class="fa-solid fa-angle-down"></i>
                </button>
            </div> {% endcomment %}
        </div>



    </div>
</section>
{% comment %}! <!--! description End --> {% endcomment %}


{% endblock content %}
{% comment %} *--- Content ---* {% endcomment %}


{% block swiper_js %}
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
{% endblock swiper_js %}

{% block custom_js %}
    <script src="{% static "js/class_01_detail/class_01_detail.js" %}"></script>
{% endblock custom_js  %}

templates/class_02_detail copy.html
{% extends "base.html" %}
{% load static %}

{% block title %}Class 02 detail{% endblock title %}

{% comment %} {% block custom_favicon %}{% endblock custom_favicon %} {% endcomment %}

{% block swiper_css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
{% endblock swiper_css %}

{% block custom_css %} 
<link rel="stylesheet" href="{% static 'css/class_02_detail/style.css' %}">
<link rel="stylesheet" href="{% static 'css/class_02_detail/responsive.css' %}">
{% endblock custom_css %}


{% comment %} *--- Content ---* {% endcomment %}
{% block content %}


{% comment %}? portfolio Start {% endcomment %}
<section class="portfolio">
    <div class="container">

        <div class="portfolioTop">
            <div class="portfolioStatus">
                limited premium class
            </div>
            <h1 class="portfolioTitle">
                Premium Class
            </h1>
            <div class="portfolioInfo">
                A 7-days training program designed to boost your strength & endurance over the course of a week.
            </div>
        </div>
        <div class="portfolioGallery">
            <img  class="some-icon-light" src="{% static 'assets/images/class_02_detail/portfolio/portfolioGallery_light.png' %}" alt="">
            <img class="some-icon-dark" src="{% static 'assets/images/class_02_detail/portfolio/portfolioGallery_dark.png' %}" alt="">
        </div>

    </div>
</section> 
{% comment %}! portfolio End {% endcomment %}


{% comment %}? book_class Start {% endcomment %}
<div class="book__class">
    <div class="container">

        <div class="trainer__book">
            <div class="trainer__class">
                <div class="trainer__about">
                    <div class="green__label">
                        <h4>exclusive trainer</h4>
                    </div>
                    <div class="trainer__image"><img src="{% static 'assets/images/class_02_detail/book_class/trainer.png' %}"></div>
                    <div class="trainer__subtitle">
                        <h2>Darianna Hammers</h2>
                        <p>Yoga Master</p>
                    </div>
                </div>
                <div class="class__about">
                    <div class="class__parametres">
                        <div class="class__details">
                            <ul>
                                <li>
                                    <div class="left">
                                        <div class="class__icon">
                                            {% comment %} <img src="./images/time.svg"> {% endcomment %}
                                            <i class="fa-regular fa-calendar-days"></i>
                                        </div>
                                        <div class="class__content">Time</div>
                                    </div>
                                    <div class="right">
                                        <p>7 days</p>
                                    </div>
                                </li>

                                <li>
                                    <div class="left">
                                        <div class="class__icon">
                                            {% comment %} <img src="./images/duration.svg"> {% endcomment %}
                                            <i class="fa-regular fa-clock"></i>
                                        </div>
                                        <div class="class__content">Average duration</div>
                                    </div>
                                    <div class="right">
                                        <p>20 minutes</p>
                                    </div>
                                </li>

                                <li>
                                    <div class="left">
                                        <div class="class__icon">
                                            {% comment %} <img src="./images/degree.svg"> {% endcomment %}
                                            <i class="fa-solid fa-sliders"></i>
                                        </div>
                                        <div class="class__content">Difficulty</div>
                                    </div>
                                    <div class="right">
                                        <p>Beginner</p>
                                    </div>
                                </li>


                                <li>
                                    <div class="left">
                                        <div class="class__icon">
                                            {% comment %} <img src="./images/intens.svg"> {% endcomment %}
                                            {% comment %} <i class="fa-solid fa-sliders"></i> {% endcomment %}
                                            <i class="fa-solid fa-signal"></i>
                                        </div>
                                        <div class="class__content">Intensity</div>
                                    </div>
                                    <div class="right">
                                        <p>Level 2</p>
                                    </div>
                                </li>

                            </ul>
                
                        </div>
                        <div class="note">
                            <p>A seven-day bodyweight training program designed to boost your strength and endurance
                                over the course of a week.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="workout__time">
                <div class="workouttime__head">
                    <div class="workouttime__icon">
                        {% comment %} <img src="./images/calendar.svg"> {% endcomment %}
                        <i class="fa-solid fa-calendar-days"></i>
                    </div>
                    <div class="workouttime__title">
                        <h1>Work-out time</h1>
                    </div>
                </div>
                <div class="workouttime__body">
                    <div class="workouttime__control">
                        <button class="date__prev">
                            {% comment %} <img src="./images/left__arrow.svg"> {% endcomment %}
                            <i class="fa-solid fa-arrow-left"></i>
                        </button>
                        <div class="workouttime__date">Friday, March 5, 2021</div>
                        <button class="date__next">
                            {% comment %} <img src="./images/right__arrow.svg"> {% endcomment %}
                            <i class="fa-solid fa-arrow-right"></i>
                        </button>
                    </div>
                    <div class="date__options">
                        <button class="date__option">07:00 AM</button>
                        <button class="date__option">11:00 AM</button>
                        <button class="date__option_df">More</button>
                    </div>
                    <div class="workouttime__btns">
                        <button class="lock__button">
                            {% comment %} <img src="./images/lock.svg"> {% endcomment %}
                            <i class="fa-solid fa-lock"></i>
                        </button>
                        <button class="book__button">Book Now</button>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>
{% comment %}! book_class End {% endcomment %}


{% comment %}? <!-- ? progams Start --> {% endcomment %}
{% include "includes_partials/programs.html" with text="You may interested"  %}
{% comment %}! <!-- ! programs End --> {% endcomment %}





{% endblock content %}
{% comment %} *--- Content ---* {% endcomment %}

{% block swiper_js %}
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
{% endblock swiper_js %}


{% block custom_js %}
    <script src="{% static '/js/class_02_detail/class_02_detail.js' %}"></script>r
{% endblock custom_js  %}

templates/class_02_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Class 02 detail{% endblock title %}

{% comment %} {% block custom_favicon %}{% endblock custom_favicon %} {% endcomment %}

{% block swiper_css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
{% endblock swiper_css %}

{% block custom_css %} 
<link rel="stylesheet" href="{% static 'css/class_02_detail/style.css' %}">
<link rel="stylesheet" href="{% static 'css/class_02_detail/responsive.css' %}">
{% endblock custom_css %}


{% comment %} *--- Content ---* {% endcomment %}
{% block content %}


{% comment %}? portfolio Start {% endcomment %}
<section class="portfolio">
    <div class="container">

        <div class="portfolioTop">
            <div class="portfolioStatus">
                limited premium class
            </div>
            <h1 class="portfolioTitle">
                Premium Class
            </h1>
            <div class="portfolioInfo">
                A 7-days training program designed to boost your strength & endurance over the course of a week.
            </div>
        </div>
        <div class="portfolioGallery">
            <img  class="some-icon-light" src="{% static 'assets/images/class_02_detail/portfolio/portfolioGallery_light.png' %}" alt="">
            <img class="some-icon-dark" src="{% static 'assets/images/class_02_detail/portfolio/portfolioGallery_dark.png' %}" alt="">
        </div>

    </div>
</section> 
{% comment %}! portfolio End {% endcomment %}


{% comment %}? book_class Start {% endcomment %}
<div class="book__class">
    <div class="container">

        <div class="trainer__book">
            <div class="trainer__class">
                <div class="trainer__about">
                    <div class="green__label">
                        <h4>exclusive trainer</h4>
                    </div>
                    <div class="trainer__image">
                        {% comment %} <img src="{% static 'assets/images/class_02_detail/book_class/trainer.png' %}"> {% endcomment %}
                        <img src="{{course.trainer.image.url}}">
                    </div>
                    <div class="trainer__subtitle">
                        {% comment %} <h2>Darianna Hammers</h2> {% endcomment %}
                        <h2>{{course.trainer.fullname}}</h2>
                        <p>{{course.trainer.profession}}</p>
                    </div>
                </div>
                <div class="class__about">
                    <div class="class__parametres">
                        <div class="class__details">
                            <ul>
                                <li>
                                    <div class="left">
                                        <div class="class__icon">
                                            {% comment %} <img src="./images/time.svg"> {% endcomment %}
                                            <i class="fa-regular fa-calendar-days"></i>
                                        </div>
                                        <div class="class__content">Time</div>
                                    </div>
                                    <div class="right">
                                        <p>7 days</p>
                                    </div>
                                </li>

                                <li>
                                    <div class="left">
                                        <div class="class__icon">
                                            {% comment %} <img src="./images/duration.svg"> {% endcomment %}
                                            <i class="fa-regular fa-clock"></i>
                                        </div>
                                        <div class="class__content">Average duration</div>
                                    </div>
                                    <div class="right">
                                        <p>{{course.duration}} minutes</p>
                                    </div>
                                </li>

                                <li>
                                    <div class="left">
                                        <div class="class__icon">
                                            {% comment %} <img src="./images/degree.svg"> {% endcomment %}
                                            <i class="fa-solid fa-sliders"></i>
                                        </div>
                                        <div class="class__content">Difficulty</div>
                                    </div>
                                    <div class="right">
                                        <p>{{course.level}}</p>
                                    </div>
                                </li>


                                <li>
                                    <div class="left">
                                        <div class="class__icon">
                                            {% comment %} <img src="./images/intens.svg"> {% endcomment %}
                                            {% comment %} <i class="fa-solid fa-sliders"></i> {% endcomment %}
                                            <i class="fa-solid fa-signal"></i>
                                        </div>
                                        <div class="class__content">Intensity</div>
                                    </div>
                                    <div class="right">
                                        <p>{{course.intensity}}</p>
                                    </div>
                                </li>

                            </ul>
                
                        </div>
                        <div class="note">
                            <p>A seven-day bodyweight training program designed to boost your strength and endurance
                                over the course of a week.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="workout__time">
                <div class="workouttime__head">
                    <div class="workouttime__icon">
                        {% comment %} <img src="./images/calendar.svg"> {% endcomment %}
                        <i class="fa-solid fa-calendar-days"></i>
                    </div>
                    <div class="workouttime__title">
                        <h1>Work-out time</h1>
                    </div>
                </div>
                <div class="workouttime__body">
                    <div class="workouttime__control">
                        <button class="date__prev">
                            {% comment %} <img src="./images/left__arrow.svg"> {% endcomment %}
                            <i class="fa-solid fa-arrow-left"></i>
                        </button>
                        <div class="workouttime__date">Friday, March 5, 2021</div>
                        <button class="date__next">
                            {% comment %} <img src="./images/right__arrow.svg"> {% endcomment %}
                            <i class="fa-solid fa-arrow-right"></i>
                        </button>
                    </div>
                    <div class="date__options">
                        <button class="date__option">07:00 AM</button>
                        <button class="date__option">11:00 AM</button>
                        <button class="date__option_df">More</button>
                    </div>
                    <div class="workouttime__btns">
                        <button class="lock__button">
                            <i class="fa-solid fa-lock"></i>
                        </button>
                        {% comment %}  {% endcomment %}
                        {% if user.is_authenticated %}
                            {% if course in user.courses_joined.all %}
                                <!-- Unenroll Form -->
                                <form class="" action="{% url 'courses:release_course' course.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="book__button release_btn">Unenroll now</button>
                                </form>
                            {% else %}
                                <!-- Enroll Form -->
                                <form class="" action="{% url 'courses:enroll_course' course.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="book__button enroll_btn">Book now</button>
                                </form>
                            {% endif %}
                        {% else %}
                            <button class="book__button"><a href="{% url 'accounts:login' %}">log in</a></button>
                        {% endif %}
                        {% comment %}  {% endcomment %}
                        {% comment %} <button class="book__button">Book Now</button> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>
{% comment %}! book_class End {% endcomment %}


{% comment %}? <!-- ? progams Start --> {% endcomment %}
{% include "includes_partials/programs.html" with text="You may interested"  %}
{% comment %}! <!-- ! programs End --> {% endcomment %}





{% endblock content %}
{% comment %} *--- Content ---* {% endcomment %}

{% block swiper_js %}
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
{% endblock swiper_js %}


{% block custom_js %}
    <script src="{% static '/js/class_02_detail/class_02_detail.js' %}"></script>r
{% endblock custom_js  %}